services:
  app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "${APP_PORT}:8080"

  postgres:
    image: 'postgres:latest'
    env_file: .env
    ports:
      - '5432:5432'